# Generated by Django 4.1.9 on 2023-06-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.PositiveIntegerField(max_length=10)),
                ('aname', models.CharField(max_length=20)),
                ('apass', models.IntegerField(max_length=50)),
            ],
        ),
    ]
