# Generated by Django 4.1.9 on 2023-06-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='admin',
            name='apass',
            field=models.IntegerField(),
        ),
    ]
