# Generated by Django 4.1.9 on 2023-06-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0009_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='oldpeak',
            field=models.FloatField(),
        ),
    ]
