# Generated by Django 4.1.9 on 2023-06-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0004_admin_delete_supadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='adminn',
        ),
    ]
