# Generated by Django 4.1.9 on 2023-06-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0007_adminsup_delete_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adminsup',
            new_name='Supadmin',
        ),
    ]
