# Generated by Django 4.1.9 on 2023-06-27 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0010_alter_user_details_oldpeak'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_details',
            new_name='user_detail',
        ),
    ]
