# Generated by Django 4.1.9 on 2023-06-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0012_user_details_delete_user_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='ca',
            new_name='bps',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='chol',
            new_name='diabi',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='exng',
            new_name='es',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='fbs',
            new_name='fati',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='num',
            new_name='hr',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='restecg',
            new_name='ioh',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='slp',
            new_name='nov',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='thal',
            new_name='sob',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='oldpeak',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='thalach',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='trestbps',
        ),
    ]
