# Generated by Django 4.1.9 on 2023-07-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0013_rename_ca_user_details_bps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='age',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='bps',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='cp',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='diabi',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='es',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='fati',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='hr',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='ioh',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='nov',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='sex',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='sob',
            field=models.CharField(max_length=5),
        ),
    ]
