# Generated by Django 4.1.9 on 2023-07-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0014_alter_user_details_age_alter_user_details_bps_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='hr',
            new_name='hhd',
        ),
    ]
