# Generated by Django 4.1.9 on 2023-07-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0016_alter_user_details_age_alter_user_details_bps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ucity', models.CharField(max_length=10)),
                ('ustate', models.CharField(max_length=10)),
                ('ucountry', models.CharField(max_length=10)),
                ('uage', models.IntegerField()),
                ('usex', models.CharField(max_length=10)),
                ('uemail', models.EmailField(max_length=20)),
                ('ufeedb', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='user_details',
            name='city',
            field=models.CharField(default='NUll', max_length=10),
        ),
        migrations.AddField(
            model_name='user_details',
            name='country',
            field=models.CharField(default='NUll', max_length=10),
        ),
        migrations.AddField(
            model_name='user_details',
            name='state',
            field=models.CharField(default='NUll', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='bps',
            field=models.CharField(default='NUll', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='cp',
            field=models.CharField(default='NUll', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='diabi',
            field=models.CharField(default='NUll', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='es',
            field=models.CharField(default='NUll', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='fati',
            field=models.CharField(default='NUll', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='hhd',
            field=models.CharField(default='NUll', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='ioh',
            field=models.CharField(default='NUll', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='nov',
            field=models.CharField(default='NUll', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='sex',
            field=models.CharField(default='NUll', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='sob',
            field=models.CharField(default='NUll', max_length=10),
        ),
    ]
