# Generated by Django 4.1.9 on 2023-07-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0017_user_data_user_details_city_user_details_country_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_data',
            new_name='user_data1',
        ),
        migrations.AlterField(
            model_name='user_details',
            name='bps',
            field=models.CharField(default='Null', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='cp',
            field=models.CharField(default='Null', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='diabi',
            field=models.CharField(default='Null', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='es',
            field=models.CharField(default='Null', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='fati',
            field=models.CharField(default='Null', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='hhd',
            field=models.CharField(default='Null', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='ioh',
            field=models.CharField(default='Null', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='nov',
            field=models.CharField(default='Null', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='sob',
            field=models.CharField(default='Null', max_length=10),
        ),
    ]
