# Generated by Django 4.1.9 on 2023-07-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0019_rename_name_user_data1_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data1',
            name='ufeedb',
            field=models.CharField(max_length=200),
        ),
    ]
