# Generated by Django 4.1.9 on 2023-07-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0021_remove_user_data1_ucity_remove_user_data1_ustate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data1',
            name='ucountry',
            field=models.CharField(default='NUll', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_data1',
            name='uemail',
            field=models.EmailField(default='NUll', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_data1',
            name='ufeedb',
            field=models.CharField(default='NUll', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_data1',
            name='uname',
            field=models.CharField(default='NUll', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_data1',
            name='usex',
            field=models.CharField(default='NUll', max_length=10),
        ),
    ]
