# Generated by Django 4.1.9 on 2023-07-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0022_alter_user_data1_ucountry_alter_user_data1_uemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data1',
            name='uemail',
            field=models.EmailField(default='NUll', max_length=40),
        ),
    ]
